platform :ios, '8.0'
target 'THWarnPlatform' do
pod 'AFNetworking', '~> 3.2.1'
pod 'SDWebImage', '~> 4.3.3'
pod 'Masonry', '~> 1.1.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'FMDB', '~> 2.7.2'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'CocoaLumberjack', '~> 3.4.2'
pod 'RegexKitLite', '~> 4.0'
end


